function formatDate(value) {
  if (!value) return "—";
  if (value instanceof Date) {
    return value.toISOString().slice(0, 10);
  }
  const s = String(value);
  if (/^\d{4}-\d{2}-\d{2}/.test(s)) return s.slice(0, 10);
  const d = new Date(s);
  if (!Number.isNaN(d.getTime())) return d.toISOString().slice(0, 10);
  return s;
}

function formatTime(value) {
  if (!value) return "—";
  const s = String(value).trim();
  const match = s.match(/(\d{1,2}):(\d{2})/);
  if (match) return `${match[1].padStart(2, "0")}:${match[2]}`;
  return s;
}

function buildInvigilationSubject({ examDate, session }) {
  return `Invigilation Duty Notification – ${formatDate(examDate)} (${session || "—"})`;
}

function buildInvigilationText(data) {
  const {
    facultyName,
    examType,
    examName,
    examDate,
    session,
    startTime,
    endTime,
    venue,
    portalUrl = "https://iexam.kumaraguru.in/attendance/login",
  } = data;

  return `Dear ${facultyName || "Faculty"},

Greetings from Hallora – Intelligent Exam Seating & Attendance System.

You have been assigned as an Invigilator for the following examination.

Examination Details

Examination Type : ${examType || "—"}
Examination Name : ${examName || "—"}
Date             : ${formatDate(examDate)}
Session          : ${session || "—"}
Time             : ${formatTime(startTime)} – ${formatTime(endTime)}
Venue            : ${venue || "—"}

Kindly take student attendance for your allotted examination hall using the Hallora Attendance Portal within one hour of the examination commencement.

Attendance Portal
${portalUrl}

This is an automated email generated by the Hallora Examination Management System.

Regards,

Hallora – Intelligent Exam Seating & Attendance System
Examination Cell
Kumaraguru College of Technology

Email: support.iexam@kct.ac.in
`;
}

function buildInvigilationHtml(data) {
  const text = buildInvigilationText(data);
  const escaped = text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
  return `<pre style="font-family:Segoe UI,Arial,sans-serif;font-size:14px;line-height:1.5;white-space:pre-wrap;color:#1e293b;">${escaped}</pre>`;
}

module.exports = {
  formatDate,
  formatTime,
  buildInvigilationSubject,
  buildInvigilationText,
  buildInvigilationHtml,
};
