const fs = require("fs");
const path = require("path");

const p = path.join(__dirname, "..", "routes", "import.js");
let s = fs.readFileSync(p, "utf8");
const start = s.indexOf("// IMPROVED: import.js - Venue Import Section");
const endMarker = "/* =====================================================\r\n   UNDO ROUTES";
let end = s.indexOf(endMarker);
if (end < 0) {
  end = s.indexOf("/* =====================================================\n   UNDO ROUTES");
}
if (start < 0 || end < 0) {
  console.error("markers not found", start, end);
  process.exit(1);
}

const replacement = [
  "/* =====================================================",
  "   VENUE BULK IMPORT — validate preview then atomic import",
  "   Excel: Venue Name | Type | Rows | Columns | Bench Config",
  "===================================================== */",
  "async function runVenueValidation(data) {",
  '  const { validateVenueRows } = require("../utils/venueBulkImport");',
  "  return validateVenueRows(data, {",
  "    venueExists: (name, type) => Venue.existsByNameAndType(name, type),",
  "  });",
  "}",
  "",
  "router.post(",
  '  "/preview-venues",',
  "  sessionAuth,",
  '  checkRole(["admin", "faculty_incharge"]),',
  "  importLimiter,",
  '  upload.single("file"),',
  "  async (req, res) => {",
  "    try {",
  "      if (!req.file) {",
  '        return res.status(400).json({ message: "No file uploaded." });',
  "      }",
  "      if (!assertValidUpload(req, res)) return;",
  "",
  "      const workbook = xlsx.readFile(req.file.path);",
  "      const sheet = workbook.Sheets[workbook.SheetNames[0]];",
  "      const data = xlsx.utils.sheet_to_json(sheet);",
  "      const result = await runVenueValidation(data);",
  "",
  "      return res.json({",
  "        message: result.message,",
  "        ...result,",
  "      });",
  "    } catch (error) {",
  '      console.error("VENUE PREVIEW ERROR:", error);',
  "      return res.status(500).json({",
  '        message: "Failed to validate venue file",',
  "        error: error.message,",
  "      });",
  "    } finally {",
  "      if (req.file) fs.unlink(req.file.path, () => {});",
  "    }",
  "  }",
  ");",
  "",
  "router.post(",
  '  "/import-venues",',
  "  sessionAuth,",
  '  checkRole(["admin", "faculty_incharge"]),',
  "  importLimiter,",
  '  upload.single("file"),',
  "  async (req, res) => {",
  "    try {",
  "      lastVenueImport = { insertedIds: [] };",
  "",
  "      if (!req.file) {",
  '        return res.status(400).json({ message: "No file uploaded." });',
  "      }",
  "      if (!assertValidUpload(req, res)) return;",
  "",
  "      const workbook = xlsx.readFile(req.file.path);",
  "      const sheet = workbook.Sheets[workbook.SheetNames[0]];",
  "      const data = xlsx.utils.sheet_to_json(sheet);",
  "      const result = await runVenueValidation(data);",
  "",
  "      if (!result.canImport) {",
  "        return res.status(400).json({",
  '          message: result.message || "Import blocked. Please correct the errors before importing.",',
  "          error: result.message,",
  "          rows: result.rows,",
  "          validCount: result.validCount,",
  "          errorCount: result.errorCount,",
  "          total: result.total,",
  "          canImport: false,",
  "        });",
  "      }",
  "",
  "      const ownerOpts = await resolveOwnerOpts(req);",
  "      let insertedCount = 0;",
  "      const duplicates = [];",
  "      const skippedRecords = [];",
  "",
  "      for (const venue of result.rows) {",
  "        try {",
  "          const venueId = await Venue.create(",
  "            {",
  "              name: venue.name,",
  "              type: venue.type,",
  "              benchesRow: venue.benchesRow,",
  "              benchesCol: venue.benchesCol,",
  "              benchConfig: venue.benchConfig,",
  "            },",
  "            ownerOpts",
  "          );",
  "          lastVenueImport.insertedIds.push(venueId);",
  "          insertedCount++;",
  "        } catch (err) {",
  '          if (err.code === "ER_DUP_ENTRY" || err.code === "23505") {',
  "            duplicates.push(`${venue.name} (${venue.type})`);",
  "          } else {",
  "            skippedRecords.push(`${venue.name} - Database error: ${err.message}`);",
  "          }",
  "        }",
  "      }",
  "",
  "      if (duplicates.length || skippedRecords.length) {",
  "        return res.status(400).json({",
  '          message: "Import blocked. Some venues could not be inserted.",',
  "          inserted: insertedCount,",
  "          skipped: duplicates.length + skippedRecords.length,",
  "          duplicates: duplicates.length ? duplicates : undefined,",
  "          skippedRecords: skippedRecords.length ? skippedRecords : undefined,",
  "          canImport: false,",
  "        });",
  "      }",
  "",
  "      res.json({",
  '        message: "Venue import completed",',
  "        inserted: insertedCount,",
  "        skipped: 0,",
  "        validCount: result.validCount,",
  "        errorCount: 0,",
  "        canImport: true,",
  "      });",
  "    } catch (error) {",
  '      console.error("VENUE IMPORT ERROR:", error);',
  "      res.status(500).json({",
  '        message: "Venue import failed",',
  "        error: error.message,",
  "      });",
  "    } finally {",
  "      if (req.file) fs.unlink(req.file.path, () => {});",
  "    }",
  "  }",
  ");",
  "",
  "",
].join("\n");

fs.writeFileSync(p, s.slice(0, start) + replacement + s.slice(end));
console.log("Updated venue import section in", p);
